export const UserActions = {
  ADD_NEW_NODE: 'ADD_NEW_NODE',
  CANCEL_NEW_NODE: 'CANCEL_NEW_NODE',
  CLOSE_TAB: 'CLOSE_TAB',
  CREATE_FILE: 'CREATE_FILE',
  CREATE_FOLDER: 'CREATE_FOLDER',
  DELETE_FILE: 'DELETE_FILE',
  DELETE_FOLDER: 'DELETE_FOLDER',
  DELETE_NODE: 'DELETE_NODE',
  OPEN_FILE: 'OPEN_FILE',
  OPEN_HISTORY: 'OPEN_HISTORY',
  RENAME_FILE: 'RENAME_FILE',
  RENAME_FOLDER: 'RENAME_FOLDER',
  SELECT_NODE: 'SELECT_NODE',
  SELECT_TAB: 'SELECT_TAB',
};

export const RemoteActions = {
  FILE_CHANGED: 'FILE_CHANGED',
  FOLDER_CHANGED: 'FOLDER_CHANGED'
};
